/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimaster;

import enumeration.Alimentazione;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Auto;
import model.MyLibrary;

/**
 *
 * @author antoninom
 */
public class NewAuto extends javax.swing.JInternalFrame {

    String fileName = "auto.dat";
    ArrayList<Auto> list = new ArrayList<Auto>();
    
    
    /**
     * Creates new form NewAuto
     */
    public NewAuto() {
        initComponents();
        DefaultComboBoxModel lista = new DefaultComboBoxModel(Alimentazione.values());
        cmbAlimentazione.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngAlimentazione = new javax.swing.ButtonGroup();
        btnInserisci = new javax.swing.JButton();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnInserisci1 = new javax.swing.JButton();
        lblMarca1 = new javax.swing.JLabel();
        txtMarca1 = new javax.swing.JTextField();
        txtModello = new javax.swing.JTextField();
        lblModello = new javax.swing.JLabel();
        txtCilindrata = new javax.swing.JTextField();
        lblCilindrata = new javax.swing.JLabel();
        txtColore = new javax.swing.JTextField();
        lblColore = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTitolo = new javax.swing.JLabel();
        cmbAlimentazione = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuovo");

        btnInserisci.setText("Inserisci");
        btnInserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserisciActionPerformed(evt);
            }
        });

        lblMarca.setText("Marca");

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Nuovo");

        btnInserisci1.setText("Inserisci");

        lblMarca1.setText("Marca");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMarca1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarca1)
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnInserisci1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInserisci1)
                .addGap(22, 22, 22))
        );

        lblModello.setText("Modello");

        lblCilindrata.setText("Cilindrata");

        lblColore.setText("Colore");

        jLabel1.setText("Alimentazione");

        lblTitolo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitolo.setText("Inserisci i Dati");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblColore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtColore))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCilindrata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCilindrata))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModello)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModello))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMarca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbAlimentazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnInserisci)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 146, Short.MAX_VALUE)
                .addComponent(lblTitolo)
                .addGap(137, 137, 137))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModello))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCilindrata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbAlimentazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnInserisci)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserisciActionPerformed
        
        boolean error = false;
        int index = -1;
        String campoVuoto = "Inserisci un valore";
        
        
        if (txtMarca.getText().isEmpty()) {
            error = true;            
            
        }
        if (txtModello.getText().isEmpty()) {
            error = true;
        }
        if (txtColore.getText().isEmpty()) {
            error = true;
        }
        
        if (txtCilindrata.getText().isEmpty()) {
            error = true;
        }
        
        if(error == false) {
        
            String marca = txtMarca.getText();
            String modello = txtModello.getText();
            String colore = txtColore.getText();
            int cilindrata = Integer.parseInt(txtCilindrata.getText());

            Auto a = new Auto (marca, modello, null, cilindrata, colore);
            
            a.setAlimentazione((Alimentazione) cmbAlimentazione.getSelectedItem());
            
            list = MyLibrary.read(fileName);
            index = MyLibrary.searchForIstance(list, a);
            
            if (index != -1){
                JOptionPane.showMessageDialog(this, "Elemento esistente!"); 
            }else{

                File f = new File(fileName);
                if(f.exists()){
                    MyLibrary.aggiungi(fileName, a);
                    JOptionPane.showMessageDialog(this, "Dato salvato sul file esistente");
                }else{
                    try {
                        if(f.createNewFile()){
                            list.add(a);
                            MyLibrary.create(fileName, list);
                            JOptionPane.showMessageDialog(this, "Dato salvato su nuovo file");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(NewAuto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }else{
                JOptionPane.showMessageDialog(this, "Errore dati mancanti!");
            
        }
            
    }//GEN-LAST:event_btnInserisciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserisci;
    private javax.swing.JButton btnInserisci1;
    private javax.swing.JComboBox<String> cmbAlimentazione;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCilindrata;
    private javax.swing.JLabel lblColore;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblModello;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.ButtonGroup rbtngAlimentazione;
    private javax.swing.JTextField txtCilindrata;
    private javax.swing.JTextField txtColore;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMarca1;
    private javax.swing.JTextField txtModello;
    // End of variables declaration//GEN-END:variables
}
