/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ascensore.Elevator;
import java.awt.Color;
import model.Ascensore;

/**
 *
 * @author antoninom
 */
public class Palazzo extends javax.swing.JFrame {
    
     

    /**
     * Creates new form Palazzo
     */
    public Palazzo() {
         
        
        initComponents();
        txtA1.setText("0");
       
        btnA1P0.setBackground(Color.green);
        
        btnA2P0.setBackground(Color.green);
        
        btnA2P0.setBackground(Color.green);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtA1 = new javax.swing.JTextField();
        txtA2 = new javax.swing.JTextField();
        txtA3 = new javax.swing.JTextField();
        btnA1P1 = new javax.swing.JButton();
        btnA1P0 = new javax.swing.JButton();
        btnA1P2 = new javax.swing.JButton();
        btnA1P3 = new javax.swing.JButton();
        btnA2P0 = new javax.swing.JButton();
        btnA2P1 = new javax.swing.JButton();
        btnA2P2 = new javax.swing.JButton();
        btnA2P3 = new javax.swing.JButton();
        btnA3P3 = new javax.swing.JButton();
        btnA3P2 = new javax.swing.JButton();
        btnA3P1 = new javax.swing.JButton();
        btnA3P0 = new javax.swing.JButton();
        lblA1 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        lblA3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtA1.setEnabled(false);

        btnA1P1.setText("1");
        btnA1P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1P1ActionPerformed(evt);
            }
        });

        btnA1P0.setText("0");
        btnA1P0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1P0ActionPerformed(evt);
            }
        });

        btnA1P2.setText("2");
        btnA1P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1P2ActionPerformed(evt);
            }
        });

        btnA1P3.setText("3");
        btnA1P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1P3ActionPerformed(evt);
            }
        });

        btnA2P0.setText("0");

        btnA2P1.setText("1");

        btnA2P2.setText("2");

        btnA2P3.setText("3");

        btnA3P3.setText("3");

        btnA3P2.setText("2");

        btnA3P1.setText("1");

        btnA3P0.setText("0");

        lblA1.setText("Ascensore 1");

        lblA2.setText("Ascensore 2");

        lblA3.setText("Ascensore 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnA1P1)
                            .addComponent(btnA1P0)
                            .addComponent(btnA1P2)
                            .addComponent(btnA1P3))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnA2P1)
                            .addComponent(btnA2P0)
                            .addComponent(btnA2P2)
                            .addComponent(btnA2P3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnA3P1)
                            .addComponent(btnA3P0)
                            .addComponent(btnA3P2)
                            .addComponent(btnA3P3))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblA2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(txtA2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtA3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA3))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA1)
                    .addComponent(lblA2)
                    .addComponent(lblA3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnA1P3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA1P2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA1P1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA1P0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnA2P3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA2P2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA2P1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA2P0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnA3P3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA3P2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA3P1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA3P0)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA1P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1P3ActionPerformed
        
        Ascensore a1 = new Ascensore(0, 3, txtA1);
        a1.setCurrentFloor(Integer.parseInt(txtA1.getText()));
        a1.setSelectedFloor(3);
        
        
    }//GEN-LAST:event_btnA1P3ActionPerformed

    private void btnA1P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1P2ActionPerformed
        
        Ascensore a1 = new Ascensore(0, 3, txtA1);
        a1.setCurrentFloor(Integer.parseInt(txtA1.getText()));
        a1.setSelectedFloor(2);
        
    }//GEN-LAST:event_btnA1P2ActionPerformed

    private void btnA1P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1P1ActionPerformed
        
        Ascensore a1 = new Ascensore(0, 3, txtA1);
        a1.setCurrentFloor(Integer.parseInt(txtA1.getText()));
        a1.setSelectedFloor(1);
    }//GEN-LAST:event_btnA1P1ActionPerformed

    private void btnA1P0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1P0ActionPerformed
        Ascensore a1 = new Ascensore(0, 3, txtA1);
        a1.setCurrentFloor(Integer.parseInt(txtA1.getText()));
        a1.setSelectedFloor(0);
    }//GEN-LAST:event_btnA1P0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Palazzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Palazzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Palazzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Palazzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Palazzo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA1P0;
    private javax.swing.JButton btnA1P1;
    private javax.swing.JButton btnA1P2;
    private javax.swing.JButton btnA1P3;
    private javax.swing.JButton btnA2P0;
    private javax.swing.JButton btnA2P1;
    private javax.swing.JButton btnA2P2;
    private javax.swing.JButton btnA2P3;
    private javax.swing.JButton btnA3P0;
    private javax.swing.JButton btnA3P1;
    private javax.swing.JButton btnA3P2;
    private javax.swing.JButton btnA3P3;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JTextField txtA1;
    private javax.swing.JTextField txtA2;
    private javax.swing.JTextField txtA3;
    // End of variables declaration//GEN-END:variables
}
